# Generated by Django 5.0.6 on 2024-05-12 11:06

import Pomodoro_App.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('quote', models.CharField(default='When I let go of what I am, I become what I might be. ~Lao Tzu', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(upload_to='Audio/uploads/%Y/%m/%d/')),
                ('sound_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=100)),
                ('compeleted', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(default=Pomodoro_App.models.get_now_date, verbose_name='date published')),
                ('end_time', models.DateTimeField(default=Pomodoro_App.models.get_now_date, verbose_name='Time completed')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IM', 'Image'), ('CO', 'Color')], default='CO', max_length=2)),
                ('theme_image', models.ImageField(upload_to='Images/uploads/%Y/%m/%d/')),
                ('theme_color', models.CharField(max_length=10)),
                ('theme_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('short_break', models.PositiveIntegerField(default=0)),
                ('long_break', models.PositiveIntegerField(default=0)),
                ('auto_start_pomodoros', models.BooleanField(default=False)),
                ('auto_start_breaks', models.BooleanField(default=False)),
                ('number_of_interval', models.PositiveIntegerField(default=0)),
                ('published_date', models.DateTimeField(default=Pomodoro_App.models.get_now_date, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.CharField(default='Chutiye timer baj gaya', max_length=100)),
                ('send_when', models.CharField(max_length=5)),
                ('send_time', models.PositiveIntegerField(default=0)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pomodoro_App.timer')),
            ],
        ),
    ]
