# Generated by Django 5.0.2 on 2024-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pomodoro_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="compeleted",
            field=models.BooleanField(default=False),
        ),
    ]
