# Generated by Django 5.0.2 on 2024-03-22 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Pomodoro_App", "0002_tasks_compeleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="task",
            new_name="task_text",
        ),
    ]
