# Generated by Django 5.0.2 on 2024-03-27 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Pomodoro_App", "0003_rename_task_tasks_task_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocksite",
            name="timer",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="timer",
        ),
    ]
