# Generated by Django 5.0.2 on 2024-03-27 10:33

import Pomodoro_App.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pomodoro_App", "0004_remove_blocksite_timer_remove_tasks_timer"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="end_time",
            field=models.DateTimeField(
                default=Pomodoro_App.models.get_now_date,
                verbose_name="Time completed",
            ),
        ),
    ]
